### ISSUE TITLE
Clarify default skip pattern

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-opentracing#112]
From @fmhwong on gitter:

> I have a question on the skip pattern. In the spec, it says "The default value of the skip pattern excludes tracing for default endpoints defined by MicroProfile Health, Metrics and OpenAPI specification." What if I define mp.opentracing.server.skip-pattern=/foo, will /metrics, /health, /openapi still on the exclude list or not?

**Comment by fmhwong** [comment]
Another question: If I want to trace everything including `/metrics`, `/health`, and `/openapi`, what can I do to include them?

**Comment by pavolloffay** [comment]
* We might introduce a new property to disable/enable default skip.
* correct default skip pattern in the spec e.g. /health|/metrics.* -> /health|/metrics/(application|vendor|base)* - to be as specific as possible

**Comment by pavolloffay** [comment]
We decided to exclude these default endpoints from tracing even is skip pattern is overriden. For example:
`mp.opentracing.server.skip-pattern=/foo` would exclude `/foo` and all default endpoints.
