### ISSUE TITLE
Broken links in spec

### ISSUE THREAD

**Issue by fmhwong** [eclipse/microprofile-opentracing#118]
https://github.com/eclipse/microprofile-opentracing/blob/master/spec/src/main/asciidoc/configuration.asciidoc

The [server-skip-pattern] and [server-span-name] are broken links.

**Comment by pavolloffay** [comment]
Both links work well in pdf and html uploaded in https://github.com/eclipse/microprofile-opentracing/releases. Could you please double check?

**Comment by fmhwong** [comment]
I didn't know it was for the PDF.  Closing this issue.
