### ISSUE TITLE
Revisit tests for default skip pattern

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-opentracing#121]
Tests for skip pattern are supposed to verify that endpoints exposed by metrics, openapi and health are not traced.

However our test app deploys servlets (or in the future jax-rs app) mapped to endpoints defined by these specs under `/opentracing` context. The problem is that for example health check spec defines `/health` endpoint mapped to the root path. So we do not test it correctly. I am not sure how we can map a jax-rs app to root endpoint with arqullian.

The proper test should include all these specs instead of simulating them via additional servlets.

**Comment by fmhwong** [comment]
The servlets are not jax-rs and will not be traced, so the tests that use servlets will pass even without the skip pattern.

**Comment by pavolloffay** [comment]
It depends how the tracing is implemented. If it's done at the lower level then servlets would be traced.

**Comment by pavolloffay** [comment]
done in #127
