### ISSUE TITLE
TCK does not allow additional data in returnedTree

### ISSUE THREAD

**Issue by fmhwong** [eclipse/microprofile-opentracing#131]
In version 1.1 of TCK, it allows additional fields in the returnedTree which are not checked by the test.   It allows JAX-RS failed method (not annotated with `@Traced`) to have `error=true` and exception logged. In version 1.2, #94 changed this behavior and some tests failed when returnedTree contains `error=true`.

**Comment by pavolloffay** [comment]
I think it was intentional to allow additional tags in spans. The spec defined only what is required
