### ISSUE TITLE
Release 1.2.1

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-opentracing#134]
Tracking issue for 1.2.1 release.

1.2.1-RC1 https://github.com/eclipse/microprofile-opentracing/releases/tag/1.2.1-RC1

**Comment by fmhwong** [comment]
LGTM

**Comment by pavolloffay** [comment]
Based on discussion with @pilhuhn we can release this (or any patch release) without creating a review in https://projects.eclipse.org/projects/technology.microprofile and wait for one week.

I will test with smallrye to double check and release.

**Comment by pavolloffay** [comment]
Successfully tested with smallrye. I am going to cut 1.2.1

**Comment by pavolloffay** [comment]
https://github.com/eclipse/microprofile-opentracing/releases/tag/1.2.1
