### ISSUE TITLE
Support JMS

### ISSUE THREAD

**Issue by bastianbowe2000** [eclipse/microprofile-opentracing#140]
Can you please add OpenTracing support for JMS as well?

**Comment by pilhuhn** [comment]
JMS is not part of MicroProfile, so I am not sure if that is doable.

**Comment by pavolloffay** [comment]
@bastianbowe2000 hi, even JMS is not part of MicroProfile you can easily add instrumentation for it by using https://github.com/opentracing-contrib/java-jms

**Comment by pavolloffay** [comment]
I will close this as there are no plans to support JMS by MicroPprofile.
