### ISSUE TITLE
Update to OpenTracing 0.32.0

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-opentracing#150]
OpenTracing 0.32.0 has been released.

**Comment by pavolloffay** [comment]
Upstream changelog https://github.com/opentracing/opentracing-java/blob/master/CHANGELOG.md#v0320-2019-03-20

There are following breaking changes:

* `TextMap` interface changed from `TextMap extends Iterable<Map.Entry<String, String>>`  `TextMap extends TextMapInject, TextMapExtract`. 

Other changes
* deprecated `Scope SpanBuilder.startActive`, `Scope ScopeManager.active()`, finishig span via `Scope.close`
* added binary propagation
* tracer implements closable

**Comment by fmhwong** [comment]
Can we skip 0.32.0 and go to 0.33.0 directly?

**Comment by rmannibucau** [comment]
These breaking changes have 2 issues:

1. For the spec itself it is an user impacting breaking change since opentracing-api is part of MP API transitively,
2. It will imply conflicts with libraries not having upgraded (like your persistence layer or your HTTP server native integration to quote a few).

Shouldn't MP take some inspiration from EE and abstract itself from vendors?
Since MP is CDI based, a very good solution is to base all this stuff on events, this way the tracer is fully abstracted and such breaking changes are unlikely to break users.
It does not prevent to expose native types (Span, Scope, ...) through unwrap methods but it make them no more a first citizen of the API.

**Comment by pavolloffay** [comment]
> Shouldn't MP take some inspiration from EE and abstract itself from vendors?

I lean towards that in this case the tracing spec should provide an abstraction and does not expose the 3rd spec as a first-class citizen.

> It does not prevent to expose native types (Span, Scope, ...) through unwrap methods but it make them no more a first citizen of the API.

Could you be more specific and perhaps sketch concrete API? Do you mean our span/scope object could be unwrapped into OpenTracing? We don't want to provide an OpenTracing impl but rather a full separated API and at the same time allow users to wire in any OpenTracing compatible instrumentation.


We know for sure that OpenTracing project will be deprecated in favor of OpenTelemetry. Now we are in a phase of deciding how to transition to that. There are a couple of options
* deprecate OpenTracing and create a new project MicroProfile-OpenTelemetry
* rebrand this spec to MicroProfile-DistributedTracing and either create a separate tracing API and allow using OT/OTEL instrumentations, or add support for OpenTelemetry and deprecate OpenTracing.

**Comment by rmannibucau** [comment]
@pavolloffay about the API i was more thinking about designing MP-OT events which would replace the scope manager API, then all the backend is an implementation detail and the Tracer, Scope etc are no more useful anymore. The unwrap point was only a way to access underlying impl as in most EE specs, ex:  void onStartTracing(@Observes StartTracingEvent start) { start.unwrap(Span.class)  }. The supported Class would be vendor dependent but the spec could recommend to support opentracing-api types OOTB.

If opentracing+metrics+health specs will disappear in favor of a new aggregated bus called telemetry (hope so personally) then I'd be in favor of just keeping opentracing version as it is and deprecate the API until MP v3 arrives and drops them.

**Comment by tobiasstadler** [comment]
Any news on this?

**Comment by pavolloffay** [comment]
There is an ongoing discussion on the ML regarding the upgrade of OpenTracing API to 0.33.0 https://groups.google.com/d/msg/microprofile/unYFj9EpTgM/IimX0yoSDgAJ.

If people want to upgrade it would be great to comment there on there with :+1:

**Comment by pavolloffay** [comment]
superseded by https://github.com/eclipse/microprofile-opentracing/issues/178
