### ISSUE TITLE
Improve MP Open tracing release page

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-opentracing#160]
Please update the [releases](https://github.com/eclipse/microprofile-opentracing/releases) to add the links to javadoc/spec/tck. Refer to config [release](https://github.com/eclipse/microprofile-config/releases) page for an example.

**Comment by pavolloffay** [comment]
Hi @Emily-Jiang is it documented somewhere how the release page should look like? 

The Last release of MP-OT was done before the config you are referring to as an example.

**Comment by Emily-Jiang** [comment]
This release page can be updated very easily. You can just add some links.

**Comment by pavolloffay** [comment]
@Emily-Jiang changed the release page. Thanks! 

I am closing this. The future release will adhere to the same format.
