### ISSUE TITLE
Update to Jakarta EE8 APIs for MP 4.0 in Jun 2020

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-opentracing#161]

**Comment by kenfinnigan** [comment]
Re-opening as it was decided to move Jakarta EE 8 API update to MP 4.0, which now aligns with MP Open Tracing 2.0

**Comment by kenfinnigan** [comment]
@pavolloffay Will the next release for MP OpenTracing be 2.0 for MP 4.0?

If so, then this can be closed again. But I'd suggest bumping the SNAPSHOT version in master to make it clear

**Comment by pavolloffay** [comment]
This is done. The versions are being updated during the release - there is no need to do it manually.
