### ISSUE TITLE
OpenTracingBaseTests class can fail due to Maven Central blocking plain http

### ISSUE THREAD

**Issue by geoand** [eclipse/microprofile-opentracing#165]
[OpenTracingBaseTests](https://github.com/eclipse/microprofile-opentracing/blob/master/tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java#L85) relies on the default setup that Shrinkwrap does to resolve the opentracing-api artifact.

However since 15/01/2020 Maven Central has started to block plain http requests (see [this](https://support.sonatype.com/hc/en-us/articles/360041287334)) which means that if the Shrinkwrap version doesn't provide proper setup (which is the case for the version used in Quarkus), the tests end up failing with something like:

```
Caused by: java.io.IOException: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/io/opentracing/opentracing-api/0.31.0/opentracing-api-0.31.0.pom
```

One solution could be to perform some manual setup (perhaps something like):

```
Maven.configureResolver().withMavenCentralRepo(false)
                .withRemoteRepo("Maven Central", "https://repo.maven.apache.org/maven2/", "default");
```

**Comment by geoand** [comment]
cc @pavolloffay @kenfinnigan

**Comment by Emily-Jiang** [comment]
Open Liberty hits the same issue. We need to get this solved asap by changing the dependency scope to provided from tck.

**Comment by pavolloffay** [comment]
@Emily-Jiang any objections on setting the URL to use HTTPS? Or even making the URL configurable?

**Comment by fmhwong** [comment]
I'm fine with either way.

**Comment by pavolloffay** [comment]
Adding a pointer to fix in arquillian https://github.com/arquillian/arquillian-core/issues/228

**Comment by bartoszmajsak** [comment]
Just a quick heads up - 1.6.0.Final is out and that should fix your problem. Cheers!

**Comment by pavolloffay** [comment]
Released 1.3.2 and 1.2.2 with the fix

**Comment by pavolloffay** [comment]
thanks @bartoszmajsak.

I have release 1.3.2 and 1.2.2 with the workaround and submitted https://github.com/eclipse/microprofile-opentracing/pull/168 to master with arquillian version bump.

**Comment by geoand** [comment]
@pavolloffay can you also take care of updating the Quarkus TCKs when you have a chance?

**Comment by pavolloffay** [comment]
I am going to release Smallrye with the fix. Then we can update Quarkus.
