### ISSUE TITLE
Remove explicit dependency downloading from Maven Central

### ISSUE THREAD

**Issue by fmhwong** [eclipse/microprofile-opentracing#175]
https://github.com/eclipse/microprofile-opentracing/blob/9f7e75ce587ea3ae38025400f0e349eabbd4fb55/tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java#L85
explicit downloads Maven dependency from Maven Central.  Hard coding the URL may limit the flexibility to redirect the downloading from a local repository/mirror.  When running the TCK in a product build, Maven Central will be an external dependency which is undesirable.  This also increases the download traffic from Maven Central if product builds are running frequently.

**Comment by pavolloffay** [comment]
@fmhwong could you please submit a PR with a fix? This is the original codebase introduced by @Steve-Fontes. I don't know why don't we prefer a local maven repo and defer to system settings.

**Comment by fmhwong** [comment]
Do RH runtimes require OpenTracing API to be packaged in the WAR?

**Comment by pavolloffay** [comment]
I cannot speak for all of them as I honestly don't know, but I think mostly if you choose OT "extension" it will bring the API.

**Comment by pavolloffay** [comment]
@fmhwong could you please apply the same patch to master?
