### ISSUE TITLE
TCK Response Objects Asserts

### ISSUE THREAD

**Issue by radcortez** [eclipse/microprofile-opentracing#184]
With the removal of Jackson as the json provider in https://github.com/eclipse/microprofile-opentracing/pull/176/, implementations can now use their own json provider implementation, which should be jsonb, since it is already integrated in the MP Platform.

Now, Jsonb states:
> For an unspecified output type of a deserialization operation, as well as where output type is specified as Object.class, implementations MUST deserialize a JSON document using Java runtime types specified in table below:
> number to java.math.BigDecimal

This is an issue with the way we do the testing asserts. In:
https://github.com/eclipse/microprofile-opentracing/blob/85a2c99efbb61fb39f17f95d56de688cfc087f5c/tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestSpan.java#L382

We assert directly the tags map, which is a <String,Object>, so with Jsonb, the `httpStatus` response deserialization will be a BigDecimal, but our expected Object will be an Integer:
https://github.com/eclipse/microprofile-opentracing/blob/feeebbcc5912588d8c57075aa40562b5f07bb53b/tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java#L336

So, failing the test when matching the object types in equals.

I don't see any easy way to go around this. I believe we need to refactor the TCK asserts a little bit to only check for values and not types.

Any thoughts?

**Comment by fmhwong** [comment]
This has been changed in master branch in PR #162.  The intention of removing `jackson` and `opentracing-api` from the WAS was to avoid hardcoding Maven URL in the TCK.

**Comment by radcortez** [comment]
Yes I know. And I agree with the change, because it gives the freedom to implementors to use other json providers other than `jackson`.

In the case you use a `jsonb` implementation, you get the issue described. I can submit a test to reproduce it.

**Comment by pavolloffay** [comment]
@radcortez JSON-B in TCK is supported only in master. It was done in this PR https://github.com/eclipse/microprofile-opentracing/pull/162 and it will be available in OT 2.0.

The older versions of MP-OT should stick to Jackson.

**Comment by radcortez** [comment]
Great. Sorry, I didn't notice this was already done in master. Thank you!
