### ISSUE TITLE
Clarify what OpenCensus is

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-opentracing#47]
From the current MP spec:
```
Work on defining common formats for SpanContexts and implementations that use the common format is being done at http://opencensus.io/[OpenCensus].
The OpenCensus API appears very similar to OpenTracing, but support for OpenCensus Tracers will probably require a separate MicroProfile specification.
```
I am not very familiar with OpenCensus but it seems that it uses context propagation from a different project https://github.com/census-instrumentation/opencensus-specs#supported-propagation-formats. We should probably clarify this in the spec. 

I understand census as tracing library (not API) which you pull in and it provides tracing/metrics for different frameworks.

**Comment by Steve-Fontes** [comment]
Got this from http://opencensus.io/, So I'll use their wording in our doc
----------------------------------------------
The key features of OpenCensus include:
Standard wire protocols and consistent APIs for handling trace and metric data.
