### ISSUE TITLE
Clean up 1.0 Release artifacts

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile-opentracing#60]
Looks like the OpenTracing 1.0 Release page has the incorrect artifacts for the spec.  The version in the specs are indicating 1.1-SNAPSHOT instead of 1.0.  This was discussed on the gitter thread:
https://gitter.im/eclipse/microprofile-opentracing

This is specific to https://github.com/eclipse/microprofile-opentracing/releases/tag/1.0

This is also related to Issue #59

**Comment by kwsutter** [comment]
Both the spec pdf and html now indicate 1.0 Final versions.

**Comment by pavolloffay** [comment]
@kwsutter can this be closed?

**Comment by kwsutter** [comment]
Yes, resolved with Issue #59 and PR #61.  Thanks!
