### ISSUE TITLE
Bump OpenTracing version to 0.31.0

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-opentracing#62]
OpenTracing API 0.31.0 has been released https://github.com/opentracing/opentracing-java/releases/tag/0.31.0. 

There are significant changes to 0.30.0, however, 0.31.0 is very close to 1.0 and we should consider the update.

**Comment by pilhuhn** [comment]
Question is if/how much this is breaking clients that are only using what is exposed through the MP-OT apis.

**Comment by pavolloffay** [comment]
MP-OT exposes `io.opentracing.Tracer` (which includes breaking changes) interface as a CDI bean. It's optional to use it explicitly to participate in tracing.

If the clients are not explicitly participating in tracing (explicitly creating spans) then there are no breaking changes.
