### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-opentracing#72]
Hi

Is it possible to have a new release since 1.0 dependencies seems outdated?

Thanks
Romain

**Comment by pavolloffay** [comment]
@rmannibucau hi, 1.1. is scheduled for this week. It will include openTtracing-api:0.31.1 

What other dependencies do you want to update?

**Comment by rmannibucau** [comment]
It is the one which hit me. Thanks!

**Comment by pavolloffay** [comment]
https://github.com/opentracing-contrib/java-jaxrs/pull/85 uses 1.1 from staging repo. I will release 1.1 today.

**Comment by pavolloffay** [comment]
1.1 is avaiblable in central https://repo1.maven.org/maven2/org/eclipse/microprofile/opentracing/microprofile-opentracing-spec/1.1/
