### ISSUE TITLE
Operation name provider

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-opentracing#75]
The current spec strictly mandates operation name strings. However, different operation names can be used - at least for JAX-RS tracing:
* HTTP method
* path wildcards

**Comment by pilhuhn** [comment]
So if we have

    GET /foo/{name}/bar
    @Traced
    String getBla(String name) {
    ...
    }

what would be the expected result?

**Comment by pavolloffay** [comment]
`/foo/{name}/bar` or `/foo/*/bar`

**Comment by pavolloffay** [comment]
Good idea, just a note for somebody not familiar with the spec. The full URL is always added to the span as `http.url` tag.

I am wondering whether we should handle tagging path parameters in a separate issue and do it globally.

The other thing: as there is a URL tag, does it make sense to add path params as separate tags? They could be handy for query purposes as the full URL can be long and contain also query params. Is there any other use-case? @objectiser 

If we want to proceed we should decide what tag to use?
e.g. `http.path.param.<key>=<value>` or `http.path.param= <key><sep><value>`

**Comment by objectiser** [comment]
I think the query usecase is the main one.

The first is better, to make it easier to use in tooling. Although I can understand prefixing the `<key>` to avoid any potential conflicts, it is a pity as I would personally like to be able to just search based on the parameter (or key) name. They are scoped to the span representing the server request, so not sure of the risk of a conflict actually occurring with a parameter name, but I guess we need to consider it.

**Comment by pavolloffay** [comment]
Maybe for the convenience it's better to skip the prefix altogether. Here https://github.com/opentracing/specification/blob/master/semantic_conventions.yaml is the list of all officially supported tags.  I will try to play with it and report back.
