### ISSUE TITLE
JAX-RS section of spec does not state any tags required on the spans

### ISSUE THREAD

**Issue by objectiser** [eclipse/microprofile-opentracing#8]
The spec discusses creating a span for the incoming and outgoing requests, but doesn't include any requirements for tags on those spans.

For example in the OpenTracing spec these spans would need to have `span.kind` of "client" or "server", and being HTTP, they should have some[ standard tags](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table) e.g. `http.url`, `http.status_code` and `http.method`.

Is the requirement on these tags implied, as they are part of the OpenTracing spec? Just wondering whether should be explicitly mentioned to ensure they are covered in the TCK and implementations?

**Comment by pavolloffay** [comment]
Tags were added here https://github.com/eclipse/microprofile-opentracing/pull/5/files#diff-7bd4a925c695c2eb0eced3872b9b965fR113, although the spec should say that some of then have to be specified at _span creation time_ or just defer or OpenTracing spec where it is defined

**Comment by objectiser** [comment]
Ok thanks - I was just looking at the asciidoc. Will have a look at the referenced PR.
