### ISSUE TITLE
Use default value for skip-patter

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-opentracing#89]
Skip pattern #16 could have a default value to exclude metrics, health and other endpoints.

**Comment by pavolloffay** [comment]
* metrics https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/architecture.adoc#scopes `/metrics/base`, `/metrics/vendor`, `metrics/application`
* health https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/overview.adoc#rationale `/health`
* openapi https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#51-overview `/openapi`

**Comment by pavolloffay** [comment]
@kenfinnigan is there any other endpoint which should be excluded from tracing?

**Comment by pavolloffay** [comment]
I have checked the current state in thorntail `2.2.0.Final`, metrics, health nor openapi are traced.

I think these are implemented as servlets and the jax-rs instrumentation does not run on these.

**Comment by kenfinnigan** [comment]
@pavolloffay right now I believe it's just those three. However, it's worth having those exclusions configurable as I know there is talk of being able to set something other than those three for each of them

**Comment by kenfinnigan** [comment]
All endpoints are present for every deployment, if those specs are packaged.

So long as `/health` skip can be changed to `/sillydata`, that's all that matters

**Comment by pavolloffay** [comment]
Then we are fine I guess. 

At the moment the whole skippattern is configurable. But is no value is presnet it skips metrics, health amd openapi. Once for example health enpoint will be configurable we can get the value and skip it (if no other skip pattern is provided)

**Comment by pavolloffay** [comment]
Please look at https://github.com/eclipse/microprofile-opentracing/pull/95. I think the spec handles it in a generic way. I will add test for `/metrics`
